// This file is automatically generated by Firebase Studio.
// Do not edit this file manually.

// This configuration is public and can be safely included in your client-side code.
// Security is enforced by Firebase Security Rules.

function getFirebaseConfig() {
  // App Hosting automatically injects the web app config as a JSON string.
  // We parse it to get the config object.
  if (process.env.FIREBASE_WEBAPP_CONFIG) {
    try {
      return JSON.parse(process.env.FIREBASE_WEBAPP_CONFIG);
    } catch (e) {
      console.error('Failed to parse FIREBASE_WEBAPP_CONFIG', e);
    }
  }

  // Fallback for local development, using the .env file.
  return {
    apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
    authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
    projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
    storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
    messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
    appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
  };
}

export const firebaseConfig = getFirebaseConfig();
 