// This file is automatically generated by Firebase Studio.
// Do not edit this file manually.

// This configuration is public and can be safely included in your client-side code.
// Security is enforced by Firebase Security Rules.

function getFirebaseConfig() {
  // In production (App Hosting), this is set via next.config.js
  if (process.env.NEXT_PUBLIC_FIREBASE_CONFIG) {
    try {
      // The env var is a JSON string, so we need to parse it.
      return JSON.parse(process.env.NEXT_PUBLIC_FIREBASE_CONFIG);
    } catch (e) {
      console.error('Failed to parse NEXT_PUBLIC_FIREBASE_CONFIG', e);
    }
  }

  // Fallback for local development, using individual .env variables.
  // This part is what shows the error message if nothing is configured.
  return {
    apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY || 'YOUR_API_KEY_IS_MISSING',
    authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
    projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
    storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
    messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
    appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
  };
}

export const firebaseConfig = getFirebaseConfig();